name: Mi Laboratorio con Dominio Fijo (Método Directo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tus archivos como siempre
      - name: Descargar mis archivos
        uses: actions/checkout@v4

      # 2. Prepara el servidor SSH
      - name: Configurar Servidor SSH
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-server
          sudo useradd -m runner
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo service ssh start

      # --- TRADUCCIÓN DE LA GUÍA QUE ENCONTRASTE ---
      - name: Instalar y Configurar Ngrok Manualmente
        run: |
          # Paso 4 de la guía: Descargar Ngrok (usando la URL actual)
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
          
          # Paso 5 de la guía: Descomprimir el archivo (Ngrok ahora usa .tgz, no .zip)
          sudo tar -xvzf ngrok.tgz -C /usr/local/bin
          
          # Paso 7 de la guía: Autenticar tu cuenta de Ngrok
          ngrok config add-authtoken 32J94PqTyY3gqdd30p1zfcXqLDp_7dEgKrE4n5mgeAC2pjA4z
          
          # Paso 8 de la guía: Iniciar el túnel en segundo plano
          echo "Iniciando túnel Ngrok en segundo plano..."
          ngrok tcp 22 &

      # Mantiene la VPS viva
      - name: Mantener viva la conexión
        run: sleep 21000
