name: Laboratorio Kali DIRECTO (Sin Fallos)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Entorno Kali y Preparar SSH con Contraseña
        run: |
          echo "### PASO 1: Creando contenedor Kali..."
          docker run --rm -d --name kali -p 2222:22 kalilinux/kali-rolling tail -f /dev/null

          echo "### PASO 2: Instalando herramientas y servidor SSH..."
          docker exec kali apt-get update
          docker exec kali apt-get install -yq openssh-server sudo curl htop git golang-go default-jdk nodejs npm nmap sqlmap

          echo "### PASO 3: Configurando SSH para aceptar contraseña..."
          docker exec kali bash -c "useradd -m -s /bin/bash kali && echo 'kali:kali' | chpasswd && adduser kali sudo"
          docker exec kali sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          docker exec kali sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/g' /etc/ssh/sshd_config
          docker exec kali service ssh restart

      - name: Iniciar Túnel con serveo.net y Mostrar Log Completo
        run: |
          echo "### PASO 4: Iniciando el túnel con serveo.net..."
          # Redirigimos la salida COMPLETA al archivo de log
          ssh -o StrictHostKeyChecking=no -R 80:localhost:2222 serveo.net > connection.log 2>&1 &
          
          echo "### Esperando a que se establezca la conexión..."
          sleep 10
          
          echo "================================================================================"
          echo "               ¡YA BASTA DE ERRORES! AQUÍ ESTÁ EL LOG COMPLETO:"
          echo "================================================================================"
          echo ""
          echo "Busca la línea que empieza con 'Forwarding SSH' y copia el comando."
          echo "Ejemplo: ssh -p 12345 kali@serveo.net"
          echo ""
          echo "--------------------------- CONTENIDO DEL LOG ----------------------------"
          cat connection.log
          echo "--------------------------------------------------------------------------"
          echo ""
          echo "La contraseña siempre es: kali"
          echo ""
          echo "================================================================================"
          
      - name: Mantener viva la conexión
        run: sleep 21000
