name: Mi Laboratorio de Desarrollo Completo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tus archivos como siempre
      - name: Descargar mis archivos de plantilla
        uses: actions/checkout@v4

      # 2. Instala y prepara el servidor SSH
      - name: Configurar Servidor SSH
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-server
          sudo useradd -m runner
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo service ssh start

      # --- ¡AQUÍ ESTÁ LA MAGIA! INSTALACIÓN DE TODAS TUS HERRAMIENTAS ---
      - name: Instalar Entorno de Desarrollo Completo
        run: |
          # Actualiza la lista de paquetes
          sudo apt-get update
          
          # Instala todas tus herramientas y lenguajes en un solo comando
          sudo apt-get install -y \
            python3 \
            htop \
            nodejs \
            npm \
            openjdk-17-jdk \
            golang-go
          
          # Mensaje de confirmación en los logs
          echo "¡Entorno de desarrollo listo!"

      # 3. Inicia el túnel con la ACCIÓN OFICIAL de Ngrok
      - name: Iniciar Túnel Ngrok
        uses: ngrok/ngrok-action@v0.x.x
        with:
          port: 22
          authtoken: 32J94PqTyY3gqdd30p1zfcXqLDp_7dEgKrE4n5mgeAC2pjA4z # TU TOKEN DE PRUEBA

      # 4. Mantiene la VPS viva
      - name: Mantener viva la conexión
        run: sleep 21000
