name: Mi Laboratorio con Dominio Fijo (Método Oficial)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tus archivos
      - name: Descargar mis archivos
        uses: actions/checkout@v4

      # 2. Prepara el servidor SSH
      - name: Configurar Servidor SSH
        run: |
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh start

      # --- SIGUIENDO LA GUÍA OFICIAL QUE ENCONTRASTE ---
      - name: Instalar y Configurar No-IP DUC
        run: |
          # Paso 1 y 2 de la guía: Moverse al directorio y descargar
          cd /usr/local/src/
          wget http://www.noip.com/client/linux/noip-duc-linux.tar.gz
          
          # Paso 3 y 4 de la guía: Descomprimir y entrar a la carpeta
          tar xf noip-duc-linux.tar.gz
          cd noip-2.1.9-1/
          
          # Paso 5 de la guía: Compilar e instalar (esto instala 'make' y 'gcc' si faltan)
          sudo apt-get update && sudo apt-get install -y make gcc
          sudo make install
          
          # --- LA SOLUCIÓN PROFESIONAL: CREAR EL ARCHIVO DE CONFIGURACIÓN ---
          # En lugar de 'noip2 -C', creamos el archivo directamente con tus datos
          sudo bash -c 'cat <<EOF > /usr/local/etc/no-ip2.conf
          # Configuración de No-IP
          Personal=ricardocraft121@gmail.com
          Password=titaBELLA
          Host=vps-ricardo.ddns.net
          # Fin de la configuración
          EOF'
          
          # Paso final de la guía: Ejecutar el cliente
          sudo /usr/local/bin/noip2

      # Mantiene la VPS viva
      - name: Mantener viva la conexión
        run: sleep 21000
