name: Laboratorio Kali con localhost.run (CORREGIDO)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Entorno Kali y Preparar SSH
        run: |
          echo "### PASO 1: Creando un contenedor Kali Linux limpio..."
          # ¡EL CAMBIO CLAVE #1! Mapeamos el puerto 2222 del HOST al 22 del CONTENEDOR.
          docker run --rm -d --name kali -p 2222:22 kalilinux/kali-rolling tail -f /dev/null

          echo "### PASO 2: Instalando herramientas y servidor SSH DENTRO de Kali..."
          docker exec kali apt-get update
          docker exec kali apt-get install -yq \
            openssh-server \
            sudo \
            htop \
            golang-go \
            default-jdk \
            nodejs \
            npm \
            nmap \
            sqlmap 

          echo "### PASO 3: Creando usuario y contraseña para la conexión..."
          docker exec kali bash -c "useradd -m -s /bin/bash kali && echo 'kali:kali' | chpasswd && adduser kali sudo"
          docker exec kali bash -c "echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config"
          docker exec kali service ssh restart
      
      - name: Iniciar Túnel con localhost.run y Mostrar Dirección
        run: |
          echo "### PASO 4: Iniciando el túnel SSH..."
          # ¡EL CAMBIO CLAVE #2! Le decimos a localhost.run que se conecte al puerto 2222.
          ssh -o StrictHostKeyChecking=no -R 80:localhost:2222 ssh.localhost.run >/dev/null 2> connection.log &

          echo "### Esperando a que se establezca la conexión..."
          sleep 8

          echo "================================================================================"
          echo "COPIA Y PEGA EL COMANDO SSH QUE APARECE ABAJO EN TU TERMINAL:"
          echo ""
          cat connection.log
          echo ""
          echo "La contraseña es: kali"
          echo "================================================================================"

      # Mantenemos el job vivo para que te puedas conectar
      - name: Mantener viva la conexión
        run: sleep 21000
