name: VPS Kali linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Levantar Contenedor Kali, instalar todo y lanzar tmate modificado
      - name: Levantar Contenedor Kali y Lanzar tmate
        run: |
          echo "Iniciando contenedor Kali Linux..."
          # Ejecutamos un contenedor en segundo plano y le damos un nombre
          docker run -d --name kali \
            -p 2222:22 \
            kalilinux/kali-rolling \
            /bin/bash -c "
              echo '>>> Actualizando repositorios...'
              apt-get update

              echo '>>> Instalando herramientas y tmate...'
              # DEBIAN_FRONTEND evita que las instalaciones pidan confirmación
              DEBIAN_FRONTEND=noninteractive apt-get install -y \
                tmate \
                openssh-server \
                sudo \
                curl \
                htop \
                git \
                golang-go \
                default-jdk \
                nodejs \
                npm \
                python3

              echo '>>> Creando usuario y configurando permisos...'
              useradd -m -s /bin/bash kali
              echo 'kali:kali' | chpasswd
              echo 'kali ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

              # --- ¡LA SOLUCIÓN CLAVE! ---
              echo '>>> Creando configuración de tmate para ocultar la barra de estado...'
              echo 'set -g status off' > /home/kali/.tmate.conf
              chown kali:kali /home/kali/.tmate.conf

              echo '>>> Iniciando sesión de tmate en segundo plano...'
              # Ejecutamos tmate como el usuario 'kali' para que lea su .tmate.conf
              sudo -u kali tmate -S /tmp/tmate.sock new-session -d
              
              echo '>>> Esperando a que la sesión esté lista...'
              tmate -S /tmp/tmate.sock wait tmate-ready
              
              echo '---'
              echo '>>> ¡CONEXIÓN LISTA! Copia y pega esta línea en tu terminal:'
              # Mostramos la conexión SSH en los logs
              tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
              echo '---'

              # Mantenemos el contenedor vivo
              tail -f /dev/null
            "
      
      # 2. Esperar y mostrar los logs del contenedor para que la conexión sea visible
      - name: Mostrar información de conexión
        run: |
          echo "Esperando a que el contenedor se estabilice..."
          sleep 15
          echo "Logs del contenedor:"
          docker logs kali

      # 3. Mantener el job vivo durante 6 horas
      - name: Mantener viva la conexión
        run: sleep 21000
