name: Laboratorio Kali Directo (Sin Complicaciones)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Configurar los repositorios de Kali Linux
      - name: Configurar Repositorios de Kali
        run: |
          # Añadimos la clave GPG de Kali
          wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add -
          # Añadimos los repositorios a la lista de fuentes
          sudo apt-add-repository "deb https://http.kali.org/kali kali-rolling main non-free contrib"
          sudo apt-get update

      # 2. Instalar todas tus herramientas y tmate
      - name: Instalar Herramientas de Desarrollo y Pentesting
        run: |
          # El -yq evita cualquier pregunta durante la instalación
          sudo apt-get install -yq \
            tmate \
            htop \
            golang-go \
            default-jdk \
            nodejs \
            npm \
            nmap \
            sqlmap 

      # 3. ¡LA SOLUCIÓN! Desactivar la barra verde y lanzar tmate
      - name: Conexión SSH vía tmate (Sin Barra de Estado)
        uses: mxschmitt/action-tmate@v3
        with:
          # Este comando se ejecuta antes de lanzar tmate, creando el archivo de configuración
          # para desactivar la molesta barra de estado verde.
          install: |
            echo 'set -g status off' > ~/.tmate.conf
