name: Laboratorio Kali DIRECTO (con serveo.net)

on:
  workflow_dispatch:

jobs: # <-- ¡AQUÍ ESTABA EL ERROR! Faltaban los dos puntos.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Entorno Kali y Preparar SSH con Contraseña
        run: |
          echo "### PASO 1: Creando contenedor Kali..."
          docker run --rm -d --name kali -p 2222:22 kalilinux/kali-rolling tail -f /dev/null

          echo "### PASO 2: Instalando herramientas y servidor SSH..."
          docker exec kali apt-get update
          docker exec kali apt-get install -yq openssh-server sudo curl htop git golang-go default-jdk nodejs npm nmap sqlmap

          echo "### PASO 3: Configurando SSH para aceptar contraseña..."
          # CREAMOS EL USUARIO Y CONTRASEÑA
          docker exec kali bash -c "useradd -m -s /bin/bash kali && echo 'kali:kali' | chpasswd && adduser kali sudo"
          # HABILITAMOS LA AUTENTICACIÓN POR CONTRASEÑA (LA CLAVE DEL ÉXITO)
          docker exec kali sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          docker exec kali sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/g' /etc/ssh/sshd_config
          docker exec kali service ssh restart

      - name: Iniciar Túnel con serveo.net y Mostrar Acceso
        run: |
          echo "### PASO 4: Iniciando el túnel con serveo.net..."
          # Redirigimos la salida para capturarla
          ssh -o StrictHostKeyChecking=no -R 80:localhost:2222 serveo.net > connection.log 2>&1 &
          
          echo "### Esperando a que se establezca la conexión..."
          sleep 10
          
          # Extraemos la dirección de conexión del log
          CONNECTION_HOST=$(grep -o '[a-zA-Z0-9]*\.serveo\.net' connection.log | head -n 1)

          echo "================================================================================"
          echo "                      ¡ACCESO DIRECTO Y DESECHABLE!"
          echo "================================================================================"
          echo ""
          echo "COPIA Y PEGA ESTE ÚNICO COMANDO EN TU TERMINAL:"
          echo ""
          echo "ssh kali@$CONNECTION_HOST"
          echo ""
          echo "CUANDO TE PIDA LA CONTRASEÑA, ES: kali"
          echo ""
          echo "================================================================================"
          
      - name: Mantener viva la conexión
        run: sleep 21000
