name: Mi Laboratorio con Dominio Fijo (Vps-de-ricardo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tus archivos como siempre
      - name: Descargar mis archivos
        uses: actions/checkout@v4

      # 2. Prepara el servidor SSH para el usuario 'runner' que ya existe
      - name: Configurar Servidor SSH
        run: |
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo service ssh start

      # --- ¡AQUÍ ESTÁ TU DOMINIO PERSONALIZADO! ---
      # Crea el túnel inverso a Serveo.net con el nombre que elegiste.
      - name: Iniciar Túnel con Serveo
        run: |
          ssh -o StrictHostKeyChecking=no -R Vps-de-ricardo:80:localhost:22 serveo.net &

      # 4. Mantiene la VPS viva
      - name: Mantener viva la conexión
        run: sleep 21000
